version: '3.3'
services:
  frontend:
    container_name: website
    image: httpd:alpine
    ports: 
      - 80:80
    volumes:
      - type: bind
        source: /home/ec2-user/project/website/
        target: /usr/local/apache2/htdocs/
    restart: always
    networks:
      - wpnet

volumes:
  sitedata:
networks:
  wpnet:
